### ISSUE TITLE
Charge density gradient translation

### ISSUE THREAD

**Issue by rjtayl** [JuliaPhysics/SolidStateDetectors.jl#140]
When I create a tube object with a translation and apply a cylindrical charge density with a radial gradient the charge density it is assumed the gradient starts from the z-axis. For example:

![image](https://user-images.githubusercontent.com/70663575/108569296-a5333b80-72d9-11eb-9418-ebcdea40dbca.png)

Is it possible to translate the gradient so that it is centered on the object instead?

**Comment by fhagemann** [comment]
Not with the existing SSD source code, but it can easily be modified to fulfil your requirements.

As we are planning a major update on SolidStateDetectors, I would also avoid putting some work-around in the source code but rather provide a code example that you could use and modify. Once, we have refactored some parts of SSD, we will definitely take this into account and make this part of the config file read-in.

## How to solve your issue (for now)

For now, I would suggest defining a new `ChargeDensity`, something like:

```julia
using SolidStateDetectors: AbstractChargeDensity, CartesianVector, AbstractCoordinatePoint
import SolidStateDetectors: get_charge_density

# new struct for translated charge densities
struct TranslatedChargeDensity{T} <: AbstractChargeDensity{T}
    charge_density_model::AbstractChargeDensity{T}
    translate::CartesianVector{T}
end

# add get_charge_density for the newly defined charge density model
function SolidStateDetectors.get_charge_density(tcdm::TranslatedChargeDensity{T}, pt::AbstractCoordinatePoint{T})::T where {T}
    translated_pt::CartesianPoint{T} = CartesianPoint(pt) - tcdm.translate
    return get_charge_density(tcdm.charge_density_model, translated_pt)
end

# override Base.+ function for easily constructing TranslatedChargeDensity
import Base.+
(+)(cdm::AbstractChargeDensity{T}, translate::CartesianVector{T}) where {T} = TranslatedChargeDensity(cdm, translate)
(+)(cdm::TranslatedChargeDensity{T}, translate::CartesianVector{T}) where {T} = TranslatedChargeDensity(cdm.charge_density_model, translate + cdm.translate)
```

This new struct allows "translating" any of the existing charge density models.



## Minimum working example

How to implement this into your code?
Select the object in which the charge density model is saved and add the translate vector using the `+=` syntax.

My simulation is called `sim`, has precision type `T` and has a cylindrical charge density.

```julia
T = Float64
sim = Simulation{T}("BEGE.json")
calculate_electric_potential!(sim, max_refinements = 2)
plot(sim.ρ, z = 0.02)
```
![old_cd](https://user-images.githubusercontent.com/30291312/108594857-b08b7300-737c-11eb-8528-7256a5f8b0cf.png)

If I want to translate the charge density from the bulk, which Is the first entry of the `semiconductors` list, I can use the `+=` syntax:

```julia
translate = CartesianVector{T}(0,0.01,0)
sim.detector.semiconductors[1].charge_density_model += translate  # this translates the charge density
calculate_electric_potential!(sim, max_refinements = 2)
plot(sim.ρ, z = 0.02)
```
![new_cd](https://user-images.githubusercontent.com/30291312/108594887-e7fa1f80-737c-11eb-97d7-e8047a9402ee.png)

Be careful not to call `sim.detector.semiconductors[1].charge_density_model += translate` multiple times if not intended.
Every call will translate the charge density by `translate`!


```julia
translate = CartesianVector{T}(0,0.01,0)
sim.detector.semiconductors[1].charge_density_model += translate  # calling this on the already translated charge density
calculate_electric_potential!(sim, max_refinements = 2)
plot(sim.ρ, z = 0.02)
```

![new2_cd](https://user-images.githubusercontent.com/30291312/108595041-e2e9a000-737d-11eb-86b4-67465f376168.png)


Does that work for now?

**Comment by fhagemann** [comment]
Any comments from the SSD crew on implementing this in the source code before upgrading to v0.6?

**Comment by lmh91** [comment]
Well, we can think about adding a origin and normal vector to our simple impurity density models (and also charge densities). 

But in general, I think we should work on the documentation and advanced examples to show how one can define any density.

**Comment by rjtayl** [comment]
> Does that work for now?

Yes, thank you.
