### ISSUE TITLE
Switch from Formatting.jl to Format.jl

### ISSUE THREAD

**Issue by oschulz** [JuliaPhysics/SolidStateDetectors.jl#375]
Formatting.jl is unmaintained and has been deprecated in favor of Format.jl: https://github.com/JuliaIO/Formatting.jl

**Comment by fhagemann** [comment]
I already did this with the v0.9.6 release:
91bf5c10491fed22656554eae7726a75c768e67f

**Comment by oschulz** [comment]
> I already did this with the v0.9.6 release 

Ooops, sorry!
