### ISSUE TITLE
Geant4 support in SSD

### ISSUE THREAD

**Issue by fhagemann** [JuliaPhysics/SolidStateDetectors.jl#385]
Things that are still needed for full Geant4 support in SSD:

## Geometry parsing and GDML file creation
- [x] Geometry handling of `Torus` and `RegularPrism` 
  (#388)
- [x] Correct handling of composite rotations
  (#388)
- [x] Definition of all compound materials defined in `MaterialProperties.jl` in the Geant4 `materials.xml` 
  (#392)

## Running Geant4 simulations
- [x] Implement some functions to place a radioactive source and to generate Geant4 events
  - [x] Collimated, directed source
  (#390)
  - [x] Isotropic source emission
 (#390)
  - [x] Monoenergetic source (pass energy)
    (#393)
  - [x] Actual isotope (with isotope decay chains)
    (#393)
- [x] IO for Geant4 simulation output in an SSD compatible format (`DetectorHitEvents`):
   see exact format here: https://github.com/JuliaPhysics/SolidStateDetectors.jl/blob/main/src/Units.jl#L102-L113
- [x] Check that the clustering algorithms in `src/ChargeClustering` perform well
- [x] Implement and test functions to generate and save pulse shapes from Geant4 output, maybe even without the need to save the intermediate `DetectorHitEvents` if not needed
  (#395)

## Documentation
- [x] Documentation on how to use the Geant4 extensions 
- [x] Docstrings for exported/extended functions
  (#409)
- [x] Tutorial for the documentation (small code example on how to use Geant4 and SSD)
  (#398)

## Plot recipes
- [x] Add plot recipe for radioactive source 
  (#396)
  ~~Optional: add plot recipe for events (in RadiationDetectorSignals?)~~

## Testing
- [x] Add tests for the new Geant4 functionality and GDML parsing
  (#401)

**Comment by hervasa2** [comment]
Here is a list of the additions we discussed and a couple other ones that occurred to me.

- [ ] Output the total number of primaries simulated. This is needed for efficiency calculations
- [ ] Directed cone emission
- [ ] Progress bar for `run_geant4_simulation`
