### ISSUE TITLE
Refactor plot recipes - GR Support

### ISSUE THREAD

**Issue by lmh91** [JuliaPhysics/SolidStateDetectors.jl#59]

**Comment by fhagemann** [comment]
I have already spent some time to refactor the plot recipes to support the GR backend.
However, when adapting the plot recipes, they might not work as intended for PyPlot anymore.
(example: polar plots expect the angle in degree in GR and in radiants in PyPlot)\

If we prioritize fast support of GR, some plots might not be producible with PyPlot.
How should we proceed here?

**Comment by fhagemann** [comment]
This issue is related to #65.
