### ISSUE TITLE
Clarify Notation of Impurity vs Charge Density 

### ISSUE THREAD

**Issue by lmh91** [JuliaPhysics/SolidStateDetectors.jl#65]
Clarify notation of the terms of impurity vs charge density and the naming of the corresponding functions and variables.

**Comment by fhagemann** [comment]
This is a good point.
Right now, `simulation.ρ` is the effective charge density divided by `ε0`.
We might want to change the names of the fields and the corresponding functions (e.g. `get_charge_density()`) to avoid confusion.

**Comment by fhagemann** [comment]
@lmh91 and I have decided to rename `ρ` to `Qeffimp` as it describes the effective charge `Q/ε0` resulting from the ionized impurities in the depleted regions.
