### ISSUE TITLE
Fix for hexagon primitive plot recipe

### ISSUE THREAD

**Issue by rjtayl** [JuliaPhysics/SolidStateDetectors.jl#79]
Hi,

I noticed a mistake in the hexagon primitive that was added recently and I thought it would be easier to fix through here than a full pull request.

In HexagonalPrism.jl line 76 should be
`for φ in [deg2rad(30),deg2rad(90), deg2rad(150), deg2rad(210), deg2rad(270), deg2rad(330)]`
Currently the plot recipe is rotated 30 degrees relative to the rest of the geometries functions.

For example,
![image](https://user-images.githubusercontent.com/70663575/97361530-08eeb000-1876-11eb-82a2-fd8d9e5a7168.png)
versus
![image](https://user-images.githubusercontent.com/70663575/97361543-0db36400-1876-11eb-815b-131e46684824.png)

**Comment by oschulz** [comment]
Thanks @rjtayl . Could you actually make a PR, if possible? We always want the tests to run anyway.

**Comment by lmh91** [comment]
This has been solved in #82.
